name: Manual Docker Test

on: 
  push:                # Runs automatically on code change
  workflow_dispatch:   # Adds the manual "Run workflow" button

jobs:
  # This is the 'ID' of the job
  bash-hello-job:
    name: Say Hello with Bash  # This is what shows up in the UI
    runs-on: ubuntu-latest
    steps:
      - name: Greeting Step
        run: echo "Hello from a named Bash step!"

  python-hello-job:
    name: Say Hello with Python
    runs-on: ubuntu-latest
    steps:
      - name: Printing Step
        run: python3 -c "print('Hello from a named Python step!')"

  docker-build-job:
    name: Build and Run Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t my-app .

      - name: Run Container
        run: docker run my-app
